#!/usr/bin/expect -f

set timeout 1

expect_after {
    timeout { exit -1 }
}

set LMI lmi
if {[info exists env(LMI)]} {
    set LMI $env(LMI)
}

spawn {*}$LMI
expect "lmi> "
send   "	"
expect "EOF   exit  help  test"
send   "E	"
expect "EOF"
send   ""
expect "lmi> "
send   "e	"
expect "xit"
send   "		"
expect "exit"
expect "lmi> exit"
send   "\r"
expect ""
catch wait result
if {[lindex $result 3] != 0} {
    exit [expr 10 + [lindex $result 3]]
} else {
    puts "\n"
}

spawn {*}$LMI
expect "lmi> "
send   ":cd test\r"
expect ">test> "
send   "	"
expect "EOF   exit  help  list  show"
send   "l	"
expect "ist"
send   ""
expect ">test> "
send   "ex	"
expect "it"
send   " 20\r"
expect ""
catch wait result
exit [lindex $result 3]
