#!/usr/bin/expect -f
# Environment variables:
#   LMI     - path to lmi meta-command executable with optional argumenta.
#
# Arguments:
#   OUTFILE - Where to write the output of COMMAND.
#   PATH    - Command path where we change before execution.
#   PROMPT  - Prompt that is expected to appear after changing to PATH.
#   COMMAND - Command to execute on given PATH.
#
# Exits with the exit code of spawned lmi shell.

set timeout 2

expect_after {
    timeout { exit -1 }
}

set OUTFILE [open [lindex $argv 0] w]
set PROMPT [lindex $argv 2]
set LMI lmi
if {[info exists env(LMI)]} {
    set LMI $env(LMI)
}
spawn -noecho sh -c "$LMI 2> /dev/null"
expect "lmi> "
send   ":cd [lindex $argv 1]\r"
expect $PROMPT
send   "[lindex $argv 3]\r"
expect -re ".*" {}
set REG {([^\n]+)\n(.*)}
expect -re "$REG$PROMPT\s*" {
    puts -nonewline $OUTFILE [string map {"\r" ""} "$expect_out(2,string)"]
}
send   "exit\r"
expect eof

catch wait result
exit [lindex $result 3]
